2019-12-14 14:47:03,097 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:43]
2019-12-14 15:09:41,888 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:43]
2019-12-14 15:42:42,667 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 15:43:35,958 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 15:58:09,653 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 16:01:45,330 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 16:01:57,868 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 16:07:29,411 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 16:08:02,360 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 16:08:11,444 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 18:27:30,078 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 18:29:52,642 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:42]
2019-12-14 19:06:05,352 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:44]
2019-12-14 20:07:21,481 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:46]
2019-12-14 22:01:10,088 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:48]
2019-12-15 23:11:09,872 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:48]
2019-12-15 23:29:56,504 INFO: Microblog startup [in /Users/bkhanal/microblog/app/__init__.py:48]
2019-12-15 23:30:03,368 ERROR: Exception on / [GET] [in /Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bkhanal/microblog/app/routes.py", line 37, in index
    prev_url=prev_url)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/bkhanal/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/bkhanal/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/bkhanal/microblog/app/templates/base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/bkhanal/microblog/app/templates/index.html", line 15, in block "app_content"
    {% include '_post.html' %}
  File "/Users/bkhanal/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
2019-12-15 23:30:09,323 ERROR: Exception on /index [GET] [in /Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bkhanal/microblog/app/routes.py", line 37, in index
    prev_url=prev_url)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/bkhanal/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/bkhanal/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/bkhanal/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/bkhanal/microblog/app/templates/base.html", line 52, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/bkhanal/microblog/app/templates/index.html", line 15, in block "app_content"
    {% include '_post.html' %}
  File "/Users/bkhanal/microblog/app/templates/_post.html", line 3, in top-level template code
    <td><img src="{{ post.author.avatar(36) }}"></td>
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'avatar'
